<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Geolocalización de Fotos</title>
    <style>
        #map {
            height: 400px;
            width: 100%;
        }
    </style>
</head>

<body>
    <div id="map"></div>

    <script>
        function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                center: { lat: 0, lng: 0 }, // Centro del mapa
                zoom: 2 // Nivel de zoom inicial
            });

            // 
            var locations = [
                { lat: 13.568738434719785, lng: -89.03800959567448, title: 'San Antonio Masahuat' },
                { lat: 13.548728334338197, lng: -88.00217937294923, title: 'Yucuaiquín' },
                //
            ];

            // 
            locations.forEach(function (location) {
                var marker = new google.maps.Marker({
                    position: { lat: location.lat, lng: location.lng },
                    map: map,
                    title: location.title
                });
            });
        }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=TU_CLAVE_DE_API&callback=initMap" async defer></script>
</body>

</html>
